# Uncomment the next line to define a global platform for your project
# platform :ios, '12.2'

target 'Chucknorris.IO' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chucknorris.IO
	pod 'Alamofire', '~> 4.7'
	pod 'Kingfisher', '~> 4.0'

end
